import { NgModule } from '@angular/core';
import {
  BriefcaseBusiness,
  Building,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Copy,
  Expand,
  ExternalLink,
  FileText,
  Github,
  GraduationCap,
  Link,
  Linkedin,
  LucideAngularModule,
  Mail,
  MapPin,
  PencilRuler,
  Phone,
  University,
  User,
  X,
} from 'lucide-angular';

@NgModule({
  declarations: [],
  imports: [
    LucideAngularModule.pick({
      Github,
      Linkedin,
      Mail,
      Copy,
      Check,
      FileText,
      ChevronRight,
      ChevronLeft,
      Link,
      CalendarDays,
      University,
      ExternalLink,
      MapPin,
      ChevronDown,
      ChevronUp,
      Expand,
      X,
      Building,
      User,
      BriefcaseBusiness,
      PencilRuler,
      GraduationCap,
      Phone,
    }),
  ],
  exports: [LucideAngularModule],
})
export class IconsModule {}
